version: "2"
services:
  app:
    image: lushdigital/alpine-golang:latest
    command: go test -mod=vendor -v -cover ./...
    working_dir: /service
    restart: "no"
    volumes:
    - $PWD:/service:ro
    env_file: infra/test.env
    depends_on:
    - redis
  redis:
    image: redis:4
    restart: always
    logging:
      driver: none
