// Code generated by protoc-gen-go. DO NOT EDIT.
// source: timestables.proto

package protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NewQuestionRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewQuestionRequest) Reset()         { *m = NewQuestionRequest{} }
func (m *NewQuestionRequest) String() string { return proto.CompactTextString(m) }
func (*NewQuestionRequest) ProtoMessage()    {}
func (*NewQuestionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2be8e3ef30d5c8b3, []int{0}
}

func (m *NewQuestionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewQuestionRequest.Unmarshal(m, b)
}
func (m *NewQuestionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewQuestionRequest.Marshal(b, m, deterministic)
}
func (m *NewQuestionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewQuestionRequest.Merge(m, src)
}
func (m *NewQuestionRequest) XXX_Size() int {
	return xxx_messageInfo_NewQuestionRequest.Size(m)
}
func (m *NewQuestionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewQuestionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewQuestionRequest proto.InternalMessageInfo

type NewQuestionResponse struct {
	A                    int64    `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B                    int64    `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	Answer               int64    `protobuf:"varint,3,opt,name=answer,proto3" json:"answer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewQuestionResponse) Reset()         { *m = NewQuestionResponse{} }
func (m *NewQuestionResponse) String() string { return proto.CompactTextString(m) }
func (*NewQuestionResponse) ProtoMessage()    {}
func (*NewQuestionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2be8e3ef30d5c8b3, []int{1}
}

func (m *NewQuestionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewQuestionResponse.Unmarshal(m, b)
}
func (m *NewQuestionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewQuestionResponse.Marshal(b, m, deterministic)
}
func (m *NewQuestionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewQuestionResponse.Merge(m, src)
}
func (m *NewQuestionResponse) XXX_Size() int {
	return xxx_messageInfo_NewQuestionResponse.Size(m)
}
func (m *NewQuestionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewQuestionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewQuestionResponse proto.InternalMessageInfo

func (m *NewQuestionResponse) GetA() int64 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *NewQuestionResponse) GetB() int64 {
	if m != nil {
		return m.B
	}
	return 0
}

func (m *NewQuestionResponse) GetAnswer() int64 {
	if m != nil {
		return m.Answer
	}
	return 0
}

type ResultsRequest struct {
	Name                 string                         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Score                int64                          `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	Answers              []*ResultsRequest_QuestionInfo `protobuf:"bytes,4,rep,name=answers,proto3" json:"answers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *ResultsRequest) Reset()         { *m = ResultsRequest{} }
func (m *ResultsRequest) String() string { return proto.CompactTextString(m) }
func (*ResultsRequest) ProtoMessage()    {}
func (*ResultsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2be8e3ef30d5c8b3, []int{2}
}

func (m *ResultsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultsRequest.Unmarshal(m, b)
}
func (m *ResultsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultsRequest.Marshal(b, m, deterministic)
}
func (m *ResultsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultsRequest.Merge(m, src)
}
func (m *ResultsRequest) XXX_Size() int {
	return xxx_messageInfo_ResultsRequest.Size(m)
}
func (m *ResultsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResultsRequest proto.InternalMessageInfo

func (m *ResultsRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ResultsRequest) GetScore() int64 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *ResultsRequest) GetAnswers() []*ResultsRequest_QuestionInfo {
	if m != nil {
		return m.Answers
	}
	return nil
}

type ResultsRequest_QuestionInfo struct {
	A                    int64    `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B                    int64    `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	Correct              bool     `protobuf:"varint,3,opt,name=correct,proto3" json:"correct,omitempty"`
	Time                 int64    `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResultsRequest_QuestionInfo) Reset()         { *m = ResultsRequest_QuestionInfo{} }
func (m *ResultsRequest_QuestionInfo) String() string { return proto.CompactTextString(m) }
func (*ResultsRequest_QuestionInfo) ProtoMessage()    {}
func (*ResultsRequest_QuestionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2be8e3ef30d5c8b3, []int{2, 0}
}

func (m *ResultsRequest_QuestionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultsRequest_QuestionInfo.Unmarshal(m, b)
}
func (m *ResultsRequest_QuestionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultsRequest_QuestionInfo.Marshal(b, m, deterministic)
}
func (m *ResultsRequest_QuestionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultsRequest_QuestionInfo.Merge(m, src)
}
func (m *ResultsRequest_QuestionInfo) XXX_Size() int {
	return xxx_messageInfo_ResultsRequest_QuestionInfo.Size(m)
}
func (m *ResultsRequest_QuestionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultsRequest_QuestionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ResultsRequest_QuestionInfo proto.InternalMessageInfo

func (m *ResultsRequest_QuestionInfo) GetA() int64 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *ResultsRequest_QuestionInfo) GetB() int64 {
	if m != nil {
		return m.B
	}
	return 0
}

func (m *ResultsRequest_QuestionInfo) GetCorrect() bool {
	if m != nil {
		return m.Correct
	}
	return false
}

func (m *ResultsRequest_QuestionInfo) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type ResultsResponse struct {
	Rank                 int64    `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResultsResponse) Reset()         { *m = ResultsResponse{} }
func (m *ResultsResponse) String() string { return proto.CompactTextString(m) }
func (*ResultsResponse) ProtoMessage()    {}
func (*ResultsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2be8e3ef30d5c8b3, []int{3}
}

func (m *ResultsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultsResponse.Unmarshal(m, b)
}
func (m *ResultsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultsResponse.Marshal(b, m, deterministic)
}
func (m *ResultsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultsResponse.Merge(m, src)
}
func (m *ResultsResponse) XXX_Size() int {
	return xxx_messageInfo_ResultsResponse.Size(m)
}
func (m *ResultsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResultsResponse proto.InternalMessageInfo

func (m *ResultsResponse) GetRank() int64 {
	if m != nil {
		return m.Rank
	}
	return 0
}

type LeaderboardRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaderboardRequest) Reset()         { *m = LeaderboardRequest{} }
func (m *LeaderboardRequest) String() string { return proto.CompactTextString(m) }
func (*LeaderboardRequest) ProtoMessage()    {}
func (*LeaderboardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2be8e3ef30d5c8b3, []int{4}
}

func (m *LeaderboardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaderboardRequest.Unmarshal(m, b)
}
func (m *LeaderboardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaderboardRequest.Marshal(b, m, deterministic)
}
func (m *LeaderboardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaderboardRequest.Merge(m, src)
}
func (m *LeaderboardRequest) XXX_Size() int {
	return xxx_messageInfo_LeaderboardRequest.Size(m)
}
func (m *LeaderboardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaderboardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LeaderboardRequest proto.InternalMessageInfo

type LeaderboardResponse struct {
	Count                int64                       `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Users                []*LeaderboardResponse_User `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *LeaderboardResponse) Reset()         { *m = LeaderboardResponse{} }
func (m *LeaderboardResponse) String() string { return proto.CompactTextString(m) }
func (*LeaderboardResponse) ProtoMessage()    {}
func (*LeaderboardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2be8e3ef30d5c8b3, []int{5}
}

func (m *LeaderboardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaderboardResponse.Unmarshal(m, b)
}
func (m *LeaderboardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaderboardResponse.Marshal(b, m, deterministic)
}
func (m *LeaderboardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaderboardResponse.Merge(m, src)
}
func (m *LeaderboardResponse) XXX_Size() int {
	return xxx_messageInfo_LeaderboardResponse.Size(m)
}
func (m *LeaderboardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaderboardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LeaderboardResponse proto.InternalMessageInfo

func (m *LeaderboardResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *LeaderboardResponse) GetUsers() []*LeaderboardResponse_User {
	if m != nil {
		return m.Users
	}
	return nil
}

type LeaderboardResponse_User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Rank                 int64    `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"`
	Score                float32  `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaderboardResponse_User) Reset()         { *m = LeaderboardResponse_User{} }
func (m *LeaderboardResponse_User) String() string { return proto.CompactTextString(m) }
func (*LeaderboardResponse_User) ProtoMessage()    {}
func (*LeaderboardResponse_User) Descriptor() ([]byte, []int) {
	return fileDescriptor_2be8e3ef30d5c8b3, []int{5, 0}
}

func (m *LeaderboardResponse_User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaderboardResponse_User.Unmarshal(m, b)
}
func (m *LeaderboardResponse_User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaderboardResponse_User.Marshal(b, m, deterministic)
}
func (m *LeaderboardResponse_User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaderboardResponse_User.Merge(m, src)
}
func (m *LeaderboardResponse_User) XXX_Size() int {
	return xxx_messageInfo_LeaderboardResponse_User.Size(m)
}
func (m *LeaderboardResponse_User) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaderboardResponse_User.DiscardUnknown(m)
}

var xxx_messageInfo_LeaderboardResponse_User proto.InternalMessageInfo

func (m *LeaderboardResponse_User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *LeaderboardResponse_User) GetRank() int64 {
	if m != nil {
		return m.Rank
	}
	return 0
}

func (m *LeaderboardResponse_User) GetScore() float32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func init() {
	proto.RegisterType((*NewQuestionRequest)(nil), "timestables.NewQuestionRequest")
	proto.RegisterType((*NewQuestionResponse)(nil), "timestables.NewQuestionResponse")
	proto.RegisterType((*ResultsRequest)(nil), "timestables.ResultsRequest")
	proto.RegisterType((*ResultsRequest_QuestionInfo)(nil), "timestables.ResultsRequest.QuestionInfo")
	proto.RegisterType((*ResultsResponse)(nil), "timestables.ResultsResponse")
	proto.RegisterType((*LeaderboardRequest)(nil), "timestables.LeaderboardRequest")
	proto.RegisterType((*LeaderboardResponse)(nil), "timestables.LeaderboardResponse")
	proto.RegisterType((*LeaderboardResponse_User)(nil), "timestables.LeaderboardResponse.User")
}

func init() { proto.RegisterFile("timestables.proto", fileDescriptor_2be8e3ef30d5c8b3) }

var fileDescriptor_2be8e3ef30d5c8b3 = []byte{
	// 378 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0xc1, 0x6a, 0xe3, 0x30,
	0x10, 0xc5, 0x8e, 0x93, 0xec, 0x8e, 0x43, 0x96, 0x9d, 0x84, 0xc5, 0x78, 0x0b, 0x0d, 0x86, 0x40,
	0x4e, 0x3e, 0xa4, 0xc7, 0x5e, 0x4a, 0xe9, 0x25, 0x50, 0x4a, 0x6a, 0x5a, 0xe8, 0x55, 0xb6, 0xa7,
	0x60, 0x9a, 0x58, 0xa9, 0x64, 0x93, 0x7f, 0xea, 0x17, 0xf5, 0x4f, 0x7a, 0x2d, 0x92, 0xe5, 0xc4,
	0x4e, 0xd2, 0xdc, 0xe6, 0x8d, 0xa4, 0xa7, 0xf7, 0xde, 0x48, 0xf0, 0xb7, 0xc8, 0xd6, 0x24, 0x0b,
	0x16, 0xaf, 0x48, 0x86, 0x1b, 0xc1, 0x0b, 0x8e, 0x6e, 0xa3, 0x15, 0x8c, 0x01, 0x1f, 0x68, 0xfb,
	0x58, 0x92, 0x2c, 0x32, 0x9e, 0x47, 0xf4, 0xae, 0xaa, 0x60, 0x01, 0xa3, 0x56, 0x57, 0x6e, 0x78,
	0x2e, 0x09, 0x07, 0x60, 0x31, 0xcf, 0x9a, 0x58, 0xb3, 0x4e, 0x64, 0x31, 0x85, 0x62, 0xcf, 0xae,
	0x50, 0x8c, 0xff, 0xa0, 0xc7, 0x72, 0xb9, 0x25, 0xe1, 0x75, 0x74, 0xcb, 0xa0, 0xe0, 0xd3, 0x82,
	0x61, 0x44, 0xb2, 0x5c, 0x15, 0xd2, 0xb0, 0x23, 0x82, 0x93, 0xb3, 0x35, 0x69, 0xa6, 0xdf, 0x91,
	0xae, 0x71, 0x0c, 0x5d, 0x99, 0x70, 0x41, 0x86, 0xb0, 0x02, 0x78, 0x0b, 0xfd, 0x8a, 0x46, 0x7a,
	0xce, 0xa4, 0x33, 0x73, 0xe7, 0xb3, 0xb0, 0xe9, 0xa7, 0xcd, 0x1b, 0xd6, 0x7a, 0x17, 0xf9, 0x2b,
	0x8f, 0xea, 0x83, 0xfe, 0x0b, 0x0c, 0x9a, 0x0b, 0x67, 0x4d, 0x78, 0xd0, 0x4f, 0xb8, 0x10, 0x94,
	0x14, 0xda, 0xc5, 0xaf, 0xa8, 0x86, 0x4a, 0xb3, 0xba, 0xd9, 0x73, 0xf4, 0x56, 0x5d, 0x07, 0x53,
	0xf8, 0xb3, 0x53, 0x60, 0x12, 0x42, 0x70, 0x04, 0xcb, 0xdf, 0x0c, 0xbf, 0xae, 0x55, 0xc4, 0xf7,
	0xc4, 0x52, 0x12, 0x31, 0x67, 0x22, 0xad, 0x23, 0xfe, 0xb0, 0x60, 0xd4, 0x6a, 0x1b, 0x86, 0x31,
	0x74, 0x13, 0x5e, 0xe6, 0x85, 0xa1, 0xa8, 0x00, 0x5e, 0x43, 0xb7, 0x94, 0x2a, 0x06, 0x5b, 0xc7,
	0x30, 0x6d, 0xc5, 0x70, 0x82, 0x26, 0x7c, 0x96, 0x24, 0xa2, 0xea, 0x8c, 0x7f, 0x03, 0x8e, 0x82,
	0x38, 0x04, 0x3b, 0x4b, 0x4d, 0xea, 0x76, 0x96, 0xee, 0xc4, 0xda, 0x7b, 0xb1, 0xfb, 0x39, 0x28,
	0xff, 0xb6, 0x99, 0xc3, 0xfc, 0xcb, 0x02, 0xf7, 0x69, 0x7f, 0x23, 0x2e, 0xc1, 0x6d, 0xbc, 0x0f,
	0xbc, 0x6c, 0xc9, 0x39, 0x7e, 0x4f, 0xfe, 0xe4, 0xe7, 0x0d, 0xc6, 0xf6, 0x1d, 0xf4, 0x4d, 0x96,
	0xf8, 0xff, 0xcc, 0x8c, 0xfd, 0x8b, 0xd3, 0x8b, 0x86, 0x65, 0x09, 0x6e, 0x23, 0x8c, 0x03, 0x5d,
	0xc7, 0x43, 0x38, 0xd0, 0x75, 0x22, 0xc7, 0xb8, 0xa7, 0xff, 0xcc, 0xd5, 0x77, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xe8, 0x37, 0xb9, 0x1f, 0x48, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TimestablesClient is the client API for Timestables service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TimestablesClient interface {
	// New Question returns a randomly generated question
	NewQuestion(ctx context.Context, in *NewQuestionRequest, opts ...grpc.CallOption) (*NewQuestionResponse, error)
	// Results adds users results into the redis cache
	Results(ctx context.Context, in *ResultsRequest, opts ...grpc.CallOption) (*ResultsResponse, error)
	// Leaderboard returns the leaderboard from the redis cache
	Leaderboard(ctx context.Context, in *LeaderboardRequest, opts ...grpc.CallOption) (*LeaderboardResponse, error)
}

type timestablesClient struct {
	cc *grpc.ClientConn
}

func NewTimestablesClient(cc *grpc.ClientConn) TimestablesClient {
	return &timestablesClient{cc}
}

func (c *timestablesClient) NewQuestion(ctx context.Context, in *NewQuestionRequest, opts ...grpc.CallOption) (*NewQuestionResponse, error) {
	out := new(NewQuestionResponse)
	err := c.cc.Invoke(ctx, "/timestables.Timestables/NewQuestion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timestablesClient) Results(ctx context.Context, in *ResultsRequest, opts ...grpc.CallOption) (*ResultsResponse, error) {
	out := new(ResultsResponse)
	err := c.cc.Invoke(ctx, "/timestables.Timestables/Results", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timestablesClient) Leaderboard(ctx context.Context, in *LeaderboardRequest, opts ...grpc.CallOption) (*LeaderboardResponse, error) {
	out := new(LeaderboardResponse)
	err := c.cc.Invoke(ctx, "/timestables.Timestables/Leaderboard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TimestablesServer is the server API for Timestables service.
type TimestablesServer interface {
	// New Question returns a randomly generated question
	NewQuestion(context.Context, *NewQuestionRequest) (*NewQuestionResponse, error)
	// Results adds users results into the redis cache
	Results(context.Context, *ResultsRequest) (*ResultsResponse, error)
	// Leaderboard returns the leaderboard from the redis cache
	Leaderboard(context.Context, *LeaderboardRequest) (*LeaderboardResponse, error)
}

// UnimplementedTimestablesServer can be embedded to have forward compatible implementations.
type UnimplementedTimestablesServer struct {
}

func (*UnimplementedTimestablesServer) NewQuestion(ctx context.Context, req *NewQuestionRequest) (*NewQuestionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewQuestion not implemented")
}
func (*UnimplementedTimestablesServer) Results(ctx context.Context, req *ResultsRequest) (*ResultsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Results not implemented")
}
func (*UnimplementedTimestablesServer) Leaderboard(ctx context.Context, req *LeaderboardRequest) (*LeaderboardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Leaderboard not implemented")
}

func RegisterTimestablesServer(s *grpc.Server, srv TimestablesServer) {
	s.RegisterService(&_Timestables_serviceDesc, srv)
}

func _Timestables_NewQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimestablesServer).NewQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/timestables.Timestables/NewQuestion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimestablesServer).NewQuestion(ctx, req.(*NewQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Timestables_Results_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimestablesServer).Results(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/timestables.Timestables/Results",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimestablesServer).Results(ctx, req.(*ResultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Timestables_Leaderboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaderboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimestablesServer).Leaderboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/timestables.Timestables/Leaderboard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimestablesServer).Leaderboard(ctx, req.(*LeaderboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Timestables_serviceDesc = grpc.ServiceDesc{
	ServiceName: "timestables.Timestables",
	HandlerType: (*TimestablesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewQuestion",
			Handler:    _Timestables_NewQuestion_Handler,
		},
		{
			MethodName: "Results",
			Handler:    _Timestables_Results_Handler,
		},
		{
			MethodName: "Leaderboard",
			Handler:    _Timestables_Leaderboard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "timestables.proto",
}
